// Variables used by Scriptable.
// These must be at the very top of the file. Do not edit.
// icon-color: deep-blue; icon-glyph: flag;
/**
 * List of country names with their ISO codes and corresponding flag emojis
 * Used in the "Countries a year" widget
 */

module.exports = [
    { "country": "Afghanistan", "isoCountryCode": "AF", "emojiCode": "\uD83C\uDDE6\uD83C\uDDEB" },
    { "country": "Albania", "isoCountryCode": "AL", "emojiCode": "\uD83C\uDDE6\uD83C\uDDF1" },
    { "country": "Algeria", "isoCountryCode": "DZ", "emojiCode": "\uD83C\uDDE9\uD83C\uDDFF" },
    { "country": "Andorra", "isoCountryCode": "AD", "emojiCode": "\ud83c\udde6\ud83c\udde9" },
    { "country": "Angola", "isoCountryCode": "AO", "emojiCode": "\uD83C\uDDE6\uD83C\uDDF4" },
    { "country": "Antarctica", "isoCountryCode": "AQ", "emojiCode": "\uD83C\uDDE6\uD83C\uDDF6" },
    { "country": "Antigua and Barbuda", "isoCountryCode": "AG", "emojiCode": "\uD83C\uDDE6\uD83C\uDDEC" },
    { "country": "Argentina", "isoCountryCode": "AR", "emojiCode": "\uD83C\uDDE6\uD83C\uDDF7" },
    { "country": "Armenia", "isoCountryCode": "AM", "emojiCode": "\uD83C\uDDE6\uD83C\uDDF2" },
    { "country": "Australia", "isoCountryCode": "AU", "emojiCode": "\uD83C\uDDE6\uD83C\uDDFA" },
    { "country": "Austria", "isoCountryCode": "AT", "emojiCode": "\uD83C\uDDE6\uD83C\uDDF9" },
    { "country": "Azerbaijan", "isoCountryCode": "AZ", "emojiCode": "\uD83C\uDDE6\uD83C\uDDFF" },
    { "country": "Bahamas", "isoCountryCode": "BS", "emojiCode": "\uD83C\uDDE7\uD83C\uDDE8" },
    { "country": "Bahrain", "isoCountryCode": "BH", "emojiCode": "\uD83C\uDDE7\uD83C\uDDED" },
    { "country": "Bangladesh", "isoCountryCode": "BD", "emojiCode": "\uD83C\uDDE7\uD83C\uDDE9" },
    { "country": "Barbados", "isoCountryCode": "BB", "emojiCode": "\uD83C\uDDE7\uD83C\uDDE7" },
    { "country": "Belarus", "isoCountryCode": "BY", "emojiCode": "\uD83C\uDDE7\uD83C\uDDFE" },
    { "country": "Belgium", "isoCountryCode": "BE", "emojiCode": "\uD83C\uDDE7\uD83C\uDDEA" },
    { "country": "Belize", "isoCountryCode": "BZ", "emojiCode": "\uD83C\uDDE7\uD83C\uDDFF" },
    { "country": "Benin", "isoCountryCode": "BJ", "emojiCode": "\uD83C\uDDE7\uD83C\uDDEF" },
    { "country": "Bermuda", "isoCountryCode": "BM", "emojiCode": "\uD83C\uDDE7\uD83C\uDDF2" },
    { "country": "Bhutan", "isoCountryCode": "BT", "emojiCode": "\uD83C\uDDE7\uD83C\uDDF9" },
    { "country": "Bolivia", "isoCountryCode": "BO", "emojiCode": "\uD83C\uDDE7\uD83C\uDDF4" },
    { "country": "Bosnia and Herzegovina", "isoCountryCode": "BA", "emojiCode": "\uD83C\uDDE7\uD83C\uDDE6" },
    { "country": "Botswana", "isoCountryCode": "BW", "emojiCode": "\uD83C\uDDE7\uD83C\uDDFC" },
    { "country": "Bouvet Island", "isoCountryCode": "BV", "emojiCode": "\uD83C\uDDE7\uD83C\uDDFB" },
    { "country": "Brazil", "isoCountryCode": "BR", "emojiCode": "\uD83C\uDDE7\uD83C\uDDF7" },
    { "country": "British Indian Ocean Territory", "isoCountryCode": "IO", "emojiCode": "\uD83C\uDDEE\uD83C\uDDEE" },
    { "country": "Brunei", "isoCountryCode": "BN", "emojiCode": "\uD83C\uDDE7\uD83C\uDDF3" },
    { "country": "Bulgaria", "isoCountryCode": "BG", "emojiCode": "\uD83C\uDDE7\uD83C\uDDEC" },
    { "country": "Burkina Faso", "isoCountryCode": "BF", "emojiCode": "\uD83C\uDDE7\uD83C\uDDEB" },
    { "country": "Burundi", "isoCountryCode": "BI", "emojiCode": "\uD83C\uDDE7\uD83C\uDDEE" },
    { "country": "Cambodia", "isoCountryCode": "KH", "emojiCode": "\uD83C\uDDEE\uD83C\uDDED" },
    { "country": "Cameroon", "isoCountryCode": "CM", "emojiCode": "\uD83C\uDDE8\uD83C\uDDF2" },
    { "country": "Canada", "isoCountryCode": "CA", "emojiCode": "\uD83C\uDDE8\uD83C\uDDE6" },
    { "country": "Cape Verde", "isoCountryCode": "CV", "emojiCode": "\uD83C\uDDE8\uD83C\uDDFB" },
    { "country": "Caribbean Netherlands", "isoCountryCode": "BQ", "emojiCode": "\uD83C\uDDE7\uD83C\uDDFC" },
    { "country": "Cayman Islands", "isoCountryCode": "KY", "emojiCode": "\uD83C\uDDEE\uD83C\uDDFE" },
    { "country": "Central African Republic", "isoCountryCode": "CF", "emojiCode": "\uD83C\uDDE8\uD83C\uDDEB" },
    { "country": "Chad", "isoCountryCode": "TD", "emojiCode": "\uD83C\uDDE8\uD83C\uDDE9" },
    { "country": "Chile", "isoCountryCode": "CL", "emojiCode": "\uD83C\uDDE8\uD83C\uDDF1" },
    { "country": "China", "isoCountryCode": "CN", "emojiCode": "\uD83C\uDDE8\uD83C\uDDF3" },
    { "country": "Christmas Island", "isoCountryCode": "CX", "emojiCode": "\uD83C\uDDE8\uD83C\uDDFD" },
    { "country": "Cocos (Keeling) Islands", "isoCountryCode": "CC", "emojiCode": "\uD83C\uDDE8\uD83C\uDDE8" },
    { "country": "Colombia", "isoCountryCode": "CO", "emojiCode": "\uD83C\uDDE8\uD83C\uDDF4" },
    { "country": "Comoros", "isoCountryCode": "KM", "emojiCode": "\uD83C\uDDE8\uD83C\uDDF2" },
    { "country": "Congo (Brazzaville)", "isoCountryCode": "CG", "emojiCode": "\uD83C\uDDE8\uD83C\uDDEC" },
    { "country": "Congo (Kinshasa)", "isoCountryCode": "CD", "emojiCode": "\uD83C\uDDE8\uD83C\uDDE9" },
    { "country": "Cook Islands", "isoCountryCode": "CK", "emojiCode": "\uD83C\uDDE8\uD83C\uDDF0" },
    { "country": "Costa Rica", "isoCountryCode": "CR", "emojiCode": "\uD83C\uDDE8\uD83C\uDDF7" },
    { "country": "Croatia", "isoCountryCode": "HR", "emojiCode": "\uD83C\uDDED\uD83C\uDDF7" },
    { "country": "Cuba", "isoCountryCode": "CU", "emojiCode": "\uD83C\uDDE8\uD83C\uDDFA" },
    { "country": "CuraĂ§ao", "isoCountryCode": "CW", "emojiCode": "\uD83C\uDDE8\uD83C\uDDFC" },
    { "country": "Cyprus", "isoCountryCode": "CY", "emojiCode": "\uD83C\uDDE8\uD83C\uDDFE" },
    { "country": "Czech Republic", "isoCountryCode": "CZ", "emojiCode": "\uD83C\uDDE8\uD83C\uDDFF" },
    { "country": "Denmark", "isoCountryCode": "DK", "emojiCode": "\uD83C\uDDE9\uD83C\uDDF0" },
    { "country": "Djibouti", "isoCountryCode": "DJ", "emojiCode": "\uD83C\uDDE9\uD83C\uDDEF" },
    { "country": "Dominica", "isoCountryCode": "DM", "emojiCode": "\uD83C\uDDE9\uD83C\uDDF2" },
    { "country": "Dominican Republic", "isoCountryCode": "DO", "emojiCode": "\uD83C\uDDE9\uD83C\uDDF4" },
    { "country": "Ecuador", "isoCountryCode": "EC", "emojiCode": "\uD83C\uDDEA\uD83C\uDDE8" },
    { "country": "Egypt", "isoCountryCode": "EG", "emojiCode": "\uD83C\uDDEA\uD83C\uDDEC" },
    { "country": "El Salvador", "isoCountryCode": "SV", "emojiCode": "\uD83C\uDDEA\uD83C\uDDFB" },
    { "country": "Equatorial Guinea", "isoCountryCode": "GQ", "emojiCode": "\uD83C\uDDEA\uD83C\uDDF6" },
    { "country": "Eritrea", "isoCountryCode": "ER", "emojiCode": "\uD83C\uDDEA\uD83C\uDDF7" },
    { "country": "Estonia", "isoCountryCode": "EE", "emojiCode": "\uD83C\uDDEA\uD83C\uDDEA" },
    { "country": "Eswatini", "isoCountryCode": "SZ", "emojiCode": "\uD83C\uDDEA\uD83C\uDDFC" },
    { "country": "Ethiopia", "isoCountryCode": "ET", "emojiCode": "\uD83C\uDDEA\uD83C\uDDF9" },
    { "country": "Falkland Islands", "isoCountryCode": "FK", "emojiCode": "\uD83C\uDDEB\uD83C\uDDF0" },
    { "country": "Faroe Islands", "isoCountryCode": "FO", "emojiCode": "\uD83C\uDDEB\uD83C\uDDF4" },
    { "country": "Fiji", "isoCountryCode": "FJ", "emojiCode": "\uD83C\uDDEB\uD83C\uDDEF" },
    { "country": "Finland", "isoCountryCode": "FI", "emojiCode": "\uD83C\uDDEB\uD83C\uDDEE" },
    { "country": "France", "isoCountryCode": "FR", "emojiCode": "\uD83C\uDDEB\uD83C\uDDF7" },
    { "country": "French Guiana", "isoCountryCode": "GF", "emojiCode": "\uD83C\uDDEB\uD83C\uDDEE" },
    { "country": "French Polynesia", "isoCountryCode": "PF", "emojiCode": "\uD83C\uDDEB\uD83C\uDDEE" },
    { "country": "French Southern and Antarctic Lands", "isoCountryCode": "TF", "emojiCode": "\uD83C\uDDEB\uD83C\uDDEE" },
    { "country": "Gabon", "isoCountryCode": "GA", "emojiCode": "\uD83C\uDDEC\uD83C\uDDE6" },
    { "country": "Gambia", "isoCountryCode": "GM", "emojiCode": "\uD83C\uDDEC\uD83C\uDDF2" },
    { "country": "Georgia", "isoCountryCode": "GE", "emojiCode": "\uD83C\uDDEC\uD83C\uDDED" },
    { "country": "Germany", "isoCountryCode": "DE", "emojiCode": "\uD83C\uDDE9\uD83C\uDDEA" },
    { "country": "Ghana", "isoCountryCode": "GH", "emojiCode": "\uD83C\uDDEC\uD83C\uDDED" },
    { "country": "Gibraltar", "isoCountryCode": "GI", "emojiCode": "\uD83C\uDDEC\uD83C\uDDEE" },
    { "country": "Greece", "isoCountryCode": "GR", "emojiCode": "\uD83C\uDDEC\uD83C\uDDF7" },
    { "country": "Greenland", "isoCountryCode": "GL", "emojiCode": "\uD83C\uDDEC\uD83C\uDDF1" },
    { "country": "Grenada", "isoCountryCode": "GD", "emojiCode": "\uD83C\uDDEC\uD83C\uDDE9" },
    { "country": "Guadeloupe", "isoCountryCode": "GP", "emojiCode": "\uD83C\uDDEC\uD83C\uDDF5" },
    { "country": "Guam", "isoCountryCode": "GU", "emojiCode": "\uD83C\uDDEC\uD83C\uDDEE" },
    { "country": "Guatemala", "isoCountryCode": "GT", "emojiCode": "\uD83C\uDDEC\uD83C\uDDF9" },
    { "country": "Guernsey", "isoCountryCode": "GG", "emojiCode": "\uD83C\uDDEC\uD83C\uDDEC" },
    { "country": "Guinea", "isoCountryCode": "GN", "emojiCode": "\uD83C\uDDEC\uD83C\uDDF3" },
    { "country": "Guinea-Bissau", "isoCountryCode": "GW", "emojiCode": "\uD83C\uDDEC\uD83C\uDDFC" },
    { "country": "Guyana", "isoCountryCode": "GY", "emojiCode": "\uD83C\uDDEC\uD83C\uDDFE" },
    { "country": "Haiti", "isoCountryCode": "HT", "emojiCode": "\uD83C\uDDED\uD83C\uDDF9" },
    { "country": "Heard Island and McDonald Islands", "isoCountryCode": "HM", "emojiCode": "\uD83C\uDDED\uD83C\uDDF2" },
    { "country": "Honduras", "isoCountryCode": "HN", "emojiCode": "\uD83C\uDDED\uD83C\uDDF3" },
    { "country": "Hong Kong", "isoCountryCode": "HK", "emojiCode": "\uD83C\uDDED\uD83C\uDDF0" },
    { "country": "Hungary", "isoCountryCode": "HU", "emojiCode": "\uD83C\uDDED\uD83C\uDDFA" },
    { "country": "Iceland", "isoCountryCode": "IS", "emojiCode": "\uD83C\uDDEE\uD83C\uDDF8" },
    { "country": "India", "isoCountryCode": "IN", "emojiCode": "\uD83C\uDDEE\uD83C\uDDF3" },
    { "country": "Indonesia", "isoCountryCode": "ID", "emojiCode": "\uD83C\uDDEE\uD83C\uDDE9" },
    { "country": "Iran", "isoCountryCode": "IR", "emojiCode": "\uD83C\uDDEE\uD83C\uDDF7" },
    { "country": "Iraq", "isoCountryCode": "IQ", "emojiCode": "\uD83C\uDDEE\uD83C\uDDF6" },
    { "country": "Ireland", "isoCountryCode": "IE", "emojiCode": "\uD83C\uDDEE\uD83C\uDDEA" },
    { "country": "Isle of Man", "isoCountryCode": "IM", "emojiCode": "\uD83C\uDDEE\uD83C\uDDF2" },
    { "country": "Israel", "isoCountryCode": "IL", "emojiCode": "\uD83C\uDDEE\uD83C\uDDF1" },
    { "country": "Italy", "isoCountryCode": "IT", "emojiCode": "\uD83C\uDDEE\uD83C\uDDF9" },
    { "country": "Ivory Coast", "isoCountryCode": "CI", "emojiCode": "\uD83C\uDDE8\uD83C\uDDEE" },
    { "country": "Jamaica", "isoCountryCode": "JM", "emojiCode": "\uD83C\uDDEF\uD83C\uDDF2" },
    { "country": "Japan", "isoCountryCode": "JP", "emojiCode": "\uD83C\uDDEF\uD83C\uDDF5" },
    { "country": "Jersey", "isoCountryCode": "JE", "emojiCode": "\uD83C\uDDEF\uD83C\uDDEA" },
    { "country": "Jordan", "isoCountryCode": "JO", "emojiCode": "\uD83C\uDDEF\uD83C\uDDF4" },
    { "country": "Kazakhstan", "isoCountryCode": "KZ", "emojiCode": "\uD83C\uDDF0\uD83C\uDDFF" },
    { "country": "Kenya", "isoCountryCode": "KE", "emojiCode": "\uD83C\uDDF0\uD83C\uDDEA" },
    { "country": "Kiribati", "isoCountryCode": "KI", "emojiCode": "\uD83C\uDDF0\uD83C\uDDEE" },
    { "country": "Kuwait", "isoCountryCode": "KW", "emojiCode": "\uD83C\uDDF0\uD83C\uDDFC" },
    { "country": "Kyrgyzstan", "isoCountryCode": "KG", "emojiCode": "\uD83C\uDDF0\uD83C\uDDEC" },
    { "country": "Laos", "isoCountryCode": "LA", "emojiCode": "\uD83C\uDDF1\uD83C\uDDE6" },
    { "country": "Latvia", "isoCountryCode": "LV", "emojiCode": "\uD83C\uDDF1\uD83C\uDDFB" },
    { "country": "Lebanon", "isoCountryCode": "LB", "emojiCode": "\uD83C\uDDF1\uD83C\uDDE7" },
    { "country": "Lesotho", "isoCountryCode": "LS", "emojiCode": "\uD83C\uDDF1\uD83C\uDDF8" },
    { "country": "Liberia", "isoCountryCode": "LR", "emojiCode": "\uD83C\uDDF1\uD83C\uDDF7" },
    { "country": "Libya", "isoCountryCode": "LY", "emojiCode": "\uD83C\uDDF1\uD83C\uDDFE" },
    { "country": "Liechtenstein", "isoCountryCode": "LI", "emojiCode": "\uD83C\uDDF1\uD83C\uDDEE" },
    { "country": "Lithuania", "isoCountryCode": "LT", "emojiCode": "\uD83C\uDDF1\uD83C\uDDF9" },
    { "country": "Luxembourg", "isoCountryCode": "LU", "emojiCode": "\uD83C\uDDF1\uD83C\uDDFA" },
    { "country": "Macao", "isoCountryCode": "MO", "emojiCode": "\uD83C\uDDF2\uD83C\uDDF4" },
    { "country": "Macedonia", "isoCountryCode": "MK", "emojiCode": "\uD83C\uDDF2\uD83C\uDDF0" },
    { "country": "Madagascar", "isoCountryCode": "MG", "emojiCode": "\uD83C\uDDF2\uD83C\uDDEC" },
    { "country": "Malawi", "isoCountryCode": "MW", "emojiCode": "\uD83C\uDDF2\uD83C\uDDFC" },
    { "country": "Malaysia", "isoCountryCode": "MY", "emojiCode": "\uD83C\uDDF2\uD83C\uDDFE" },
    { "country": "Maldives", "isoCountryCode": "MV", "emojiCode": "\uD83C\uDDF2\uD83C\uDDFB" },
    { "country": "Mali", "isoCountryCode": "ML", "emojiCode": "\uD83C\uDDF2\uD83C\uDDF1" },
    { "country": "Malta", "isoCountryCode": "MT", "emojiCode": "\uD83C\uDDF2\uD83C\uDDF9" },
    { "country": "Marshall Islands", "isoCountryCode": "MH", "emojiCode": "\uD83C\uDDF2\uD83C\uDDED" },
    { "country": "Martinique", "isoCountryCode": "MQ", "emojiCode": "\uD83C\uDDF2\uD83C\uDDF6" },
    { "country": "Mauritania", "isoCountryCode": "MR", "emojiCode": "\uD83C\uDDF2\uD83C\uDDF7" },
    { "country": "Mauritius", "isoCountryCode": "MU", "emojiCode": "\uD83C\uDDF2\uD83C\uDDFA" },
    { "country": "Mayotte", "isoCountryCode": "YT", "emojiCode": "\uD83C\uDDEB\uD83C\uDDF7" },
    { "country": "Mexico", "isoCountryCode": "MX", "emojiCode": "\uD83C\uDDF2\uD83C\uDDFD" },
    { "country": "Micronesia", "isoCountryCode": "FM", "emojiCode": "\uD83C\uDDF2\uD83C\uDDF3" },
    { "country": "Moldova", "isoCountryCode": "MD", "emojiCode": "\uD83C\uDDF2\uD83C\uDDE9" },
    { "country": "Monaco", "isoCountryCode": "MC", "emojiCode": "\uD83C\uDDEE\uD83C\uDDEE" },
    { "country": "Mongolia", "isoCountryCode": "MN", "emojiCode": "\uD83C\uDDF2\uD83C\uDDF3" },
    { "country": "Montenegro", "isoCountryCode": "ME", "emojiCode": "\uD83C\uDDF2\uD83C\uDDEA" },
    { "country": "Montserrat", "isoCountryCode": "MS", "emojiCode": "\uD83C\uDDF2\uD83C\uDDF8" },
    { "country": "Morocco", "isoCountryCode": "MA", "emojiCode": "\uD83C\uDDF2\uD83C\uDDE6" },
    { "country": "Mozambique", "isoCountryCode": "MZ", "emojiCode": "\uD83C\uDDF2\uD83C\uDDFF" },
    { "country": "Myanmar", "isoCountryCode": "MM", "emojiCode": "\uD83C\uDDF2\uD83C\uDDF2" },
    { "country": "Namibia", "isoCountryCode": "NA", "emojiCode": "\uD83C\uDDF3\uD83C\uDDE6" },
    { "country": "Nauru", "isoCountryCode": "NR", "emojiCode": "\uD83C\uDDF3\uD83C\uDDF7" },
    { "country": "Nepal", "isoCountryCode": "NP", "emojiCode": "\uD83C\uDDF3\uD83C\uDDF5" },
    { "country": "Netherlands", "isoCountryCode": "NL", "emojiCode": "\uD83C\uDDF3\uD83C\uDDF1" },
    { "country": "New Caledonia", "isoCountryCode": "NC", "emojiCode": "\uD83C\uDDF3\uD83C\uDDE8" },
    { "country": "New Zealand", "isoCountryCode": "NZ", "emojiCode": "\uD83C\uDDF3\uD83C\uDDFF" },
    { "country": "Nicaragua", "isoCountryCode": "NI", "emojiCode": "\uD83C\uDDEE\uD83C\uDDEE" },
    { "country": "Niger", "isoCountryCode": "NE", "emojiCode": "\uD83C\uDDEE\uD83C\uDDEA" },
    { "country": "Nigeria", "isoCountryCode": "NG", "emojiCode": "\uD83C\uDDEE\uD83C\uDDEC" },
    { "country": "Niue", "isoCountryCode": "NU", "emojiCode": "\uD83C\uDDF3\uD83C\uDDFA" },
    { "country": "Norfolk Island", "isoCountryCode": "NF", "emojiCode": "\uD83C\uDDF3\uD83C\uDDEE" },
    { "country": "North Korea", "isoCountryCode": "KP", "emojiCode": "\uD83C\uDDF0\uD83C\uDDF5" },
    { "country": "Northern Mariana Islands", "isoCountryCode": "MP", "emojiCode": "\uD83C\uDDF2\uD83C\uDDF5" },
    { "country": "Norway", "isoCountryCode": "NO", "emojiCode": "\uD83C\uDDF3\uD83C\uDDF4" },
    { "country": "Oman", "isoCountryCode": "OM", "emojiCode": "\uD83C\uDDF4\uD83C\uDDF2" },
    { "country": "Pakistan", "isoCountryCode": "PK", "emojiCode": "\uD83C\uDDF5\uD83C\uDDF0" },
    { "country": "Palau", "isoCountryCode": "PW", "emojiCode": "\uD83C\uDDF5\uD83C\uDDFC" },
    { "country": "Palestinian Territory", "isoCountryCode": "PS", "emojiCode": "\uD83C\uDDF5\uD83C\uDDF8" },
    { "country": "Panama", "isoCountryCode": "PA", "emojiCode": "\uD83C\uDDE6\uD83C\uDDF2" },
    { "country": "Papua New Guinea", "isoCountryCode": "PG", "emojiCode": "\uD83C\uDDF5\uD83C\uDDEC" },
    { "country": "Paraguay", "isoCountryCode": "PY", "emojiCode": "\uD83C\uDDF5\uD83C\uDDFE" },
    { "country": "Peru", "isoCountryCode": "PE", "emojiCode": "\uD83C\uDDF5\uD83C\uDDEA" },
    { "country": "Philippines", "isoCountryCode": "PH", "emojiCode": "\uD83C\uDDF5\uD83C\uDDED" },
    { "country": "Pitcairn Islands", "isoCountryCode": "PN", "emojiCode": "\uD83C\uDDEE\uD83C\uDDF3" },
    { "country": "Poland", "isoCountryCode": "PL", "emojiCode": "\uD83C\uDDF5\uD83C\uDDF1" },
    { "country": "Portugal", "isoCountryCode": "PT", "emojiCode": "\uD83C\uDDF5\uD83C\uDDF9" },
    { "country": "Puerto Rico", "isoCountryCode": "PR", "emojiCode": "\uD83C\uDDE7\uD83C\uDDF7" },
    { "country": "Qatar", "isoCountryCode": "QA", "emojiCode": "\uD83C\uDDF6\uD83C\uDDE6" },
    { "country": "RĂŠunion", "isoCountryCode": "RE", "emojiCode": "\uD83C\uDDF7\uD83C\uDDEA" },
    { "country": "Romania", "isoCountryCode": "RO", "emojiCode": "\uD83C\uDDF7\uD83C\uDDF4" },
    { "country": "Russia", "isoCountryCode": "RU", "emojiCode": "\uD83C\uDDF7\uD83C\uDDFA" },
    { "country": "Rwanda", "isoCountryCode": "RW", "emojiCode": "\uD83C\uDDF7\uD83C\uDDFC" },
    { "country": "Saint BarthĂŠlemy", "isoCountryCode": "BL", "emojiCode": "\uD83C\uDDE7\uD83C\uDDF1" },
    { "country": "Saint Helena", "isoCountryCode": "SH", "emojiCode": "\uD83C\uDDED\uD83C\uDDF2" },
    { "country": "Saint Kitts and Nevis", "isoCountryCode": "KN", "emojiCode": "\uD83C\uDDF0\uD83C\uDDF3" },
    { "country": "Saint Lucia", "isoCountryCode": "LC", "emojiCode": "\uD83C\uDDED\uD83C\uDDF1" },
    { "country": "Saint Martin", "isoCountryCode": "MF", "emojiCode": "\uD83C\uDDEE\uD83C\uDDF2" },
    { "country": "Saint Pierre and Miquelon", "isoCountryCode": "PM", "emojiCode": "\uD83C\uDDEE\uD83C\uDDF2" },
    { "country": "Saint Vincent and the Grenadines", "isoCountryCode": "VC", "emojiCode": "\uD83C\uDDEB\uD83C\uDDEE" },
    { "country": "Samoa", "isoCountryCode": "WS", "emojiCode": "\uD83C\uDDFC\uD83C\uDDF8" },
    { "country": "San Marino", "isoCountryCode": "SM", "emojiCode": "\uD83C\uDDF8\uD83C\uDDF2" },
    { "country": "SĂŁo TomĂŠ and PrĂ­ncipe", "isoCountryCode": "ST", "emojiCode": "\uD83C\uDDF8\uD83C\uDDF9" },
    { "country": "Saudi Arabia", "isoCountryCode": "SA", "emojiCode": "\uD83C\uDDF8\uD83C\uDDE6" },
    { "country": "Senegal", "isoCountryCode": "SN", "emojiCode": "\uD83C\uDDF8\uD83C\uDDE3" },
    { "country": "Serbia", "isoCountryCode": "RS", "emojiCode": "\uD83C\uDDF7\uD83C\uDDF8" },
    { "country": "Seychelles", "isoCountryCode": "SC", "emojiCode": "\uD83C\uDDF8\uD83C\uDDE8" },
    { "country": "Sierra Leone", "isoCountryCode": "SL", "emojiCode": "\uD83C\uDDF8\uD83C\uDDF1" },
    { "country": "Singapore", "isoCountryCode": "SG", "emojiCode": "\uD83C\uDDF8\uD83C\uDDEC" },
    { "country": "Sint Maarten", "isoCountryCode": "SX", "emojiCode": "\uD83C\uDDF8\uD83C\uDDFD" },
    { "country": "Slovakia", "isoCountryCode": "SK", "emojiCode": "\uD83C\uDDF8\uD83C\uDDF0" },
    { "country": "Slovenia", "isoCountryCode": "SI", "emojiCode": "\uD83C\uDDF8\uD83C\uDDEE" },
    { "country": "Solomon Islands", "isoCountryCode": "SB", "emojiCode": "\uD83C\uDDF8\uD83C\uDDE7" },
    { "country": "Somalia", "isoCountryCode": "SO", "emojiCode": "\uD83C\uDDF8\uD83C\uDDF4" },
    { "country": "South Africa", "isoCountryCode": "ZA", "emojiCode": "\uD83C\uDDFF\uD83C\uDDE6" },
    { "country": "South Georgia and the South Sandwich Islands", "isoCountryCode": "GS", "emojiCode": "\uD83C\uDDEC\uD83C\uDDF8" },
    { "country": "South Korea", "isoCountryCode": "KR", "emojiCode": "\uD83C\uDDF0\uD83C\uDDF7" },
    { "country": "South Sudan", "isoCountryCode": "SS", "emojiCode": "\uD83C\uDDF0\uD83C\uDDF8" },
    { "country": "Spain", "isoCountryCode": "ES", "emojiCode": "\uD83C\uDDEA\uD83C\uDDF8" },
    { "country": "Sri Lanka", "isoCountryCode": "LK", "emojiCode": "\uD83C\uDDF1\uD83C\uDDF0" },
    { "country": "Sudan", "isoCountryCode": "SD", "emojiCode": "\uD83C\uDDF8\uD83C\uDDE9" },
    { "country": "Suriname", "isoCountryCode": "SR", "emojiCode": "\uD83C\uDDF8\uD83C\uDDF7" },
    { "country": "Svalbard and Jan Mayen", "isoCountryCode": "SJ", "emojiCode": "\uD83C\uDDF8\uD83C\uDDEF" },
    { "country": "Sweden", "isoCountryCode": "SE", "emojiCode": "\uD83C\uDDF8\uD83C\uDDEA" },
    { "country": "Switzerland", "isoCountryCode": "CH", "emojiCode": "\uD83C\uDDE8\uD83C\uDDED" },
    { "country": "Syria", "isoCountryCode": "SY", "emojiCode": "\uD83C\uDDF8\uD83C\uDDFE" },
    { "country": "Taiwan", "isoCountryCode": "TW", "emojiCode": "\uD83C\uDDF9\uD83C\uDDFC" },
    { "country": "Tajikistan", "isoCountryCode": "TJ", "emojiCode": "\uD83C\uDDF9\uD83C\uDDEF" },
    { "country": "Tanzania", "isoCountryCode": "TZ", "emojiCode": "\uD83C\uDDF9\uD83C\uDDFF" },
    { "country": "Thailand", "isoCountryCode": "TH", "emojiCode": "\uD83C\uDDF9\uD83C\uDDED" },
    { "country": "Timor-Leste", "isoCountryCode": "TL", "emojiCode": "\uD83C\uDDF9\uD83C\uDDF1" },
    { "country": "Togo", "isoCountryCode": "TG", "emojiCode": "\uD83C\uDDF9\uD83C\uDDEC" },
    { "country": "Tokelau", "isoCountryCode": "TK", "emojiCode": "\uD83C\uDDF9\uD83C\uDDF0" },
    { "country": "Tonga", "isoCountryCode": "TO", "emojiCode": "\uD83C\uDDF9\uD83C\uDDF4" },
    { "country": "Trinidad and Tobago", "isoCountryCode": "TT", "emojiCode": "\uD83C\uDDF9\uD83C\uDDF9" },
    { "country": "Tunisia", "isoCountryCode": "TN", "emojiCode": "\uD83C\uDDF9\uD83C\uDDF3" },
    { "country": "Turkey", "isoCountryCode": "TR", "emojiCode": "\uD83C\uDDF9\uD83C\uDDF7" },
    { "country": "Turkmenistan", "isoCountryCode": "TM", "emojiCode": "\uD83C\uDDF9\uD83C\uDDF2" },
    { "country": "Turks and Caicos Islands", "isoCountryCode": "TC", "emojiCode": "\uD83C\uDDF9\uD83C\uDDE8" },
    { "country": "Tuvalu", "isoCountryCode": "TV", "emojiCode": "\uD83C\uDDF9\uD83C\uDDFB" },
    { "country": "Uganda", "isoCountryCode": "UG", "emojiCode": "\uD83C\uDDFA\uD83C\uDDEC" },
    { "country": "Ukraine", "isoCountryCode": "UA", "emojiCode": "\uD83C\uDDFA\uD83C\uDDE6" },
    { "country": "United Arab Emirates", "isoCountryCode": "AE", "emojiCode": "\uD83C\uDDE6\uD83C\uDDEA" },
    { "country": "United Kingdom", "isoCountryCode": "GB", "emojiCode": "\uD83C\uDDEC\uD83C\uDDE7" },
    { "country": "United States", "isoCountryCode": "US", "emojiCode": "\uD83C\uDDFA\uD83C\uDDF8" },
    { "country": "Uruguay", "isoCountryCode": "UY", "emojiCode": "\uD83C\uDDFA\uD83C\uDDFE" },
    { "country": "Uzbekistan", "isoCountryCode": "UZ", "emojiCode": "\uD83C\uDDFA\uD83C\uDDFF" },
    { "country": "Vanuatu", "isoCountryCode": "VU", "emojiCode": "\uD83C\uDDFB\uD83C\uDDFA" },
    { "country": "Vatican City", "isoCountryCode": "VA", "emojiCode": "\uD83C\uDDFB\uD83C\uDDE6" },
    { "country": "Venezuela", "isoCountryCode": "VE", "emojiCode": "\uD83C\uDDFB\uD83C\uDDEA" },
    { "country": "Vietnam", "isoCountryCode": "VN", "emojiCode": "\uD83C\uDDFB\uD83C\uDDF3" },
    { "country": "Virgin Islands (British)", "isoCountryCode": "VG", "emojiCode": "\uD83C\uDDFB\uD83C\uDDEC" },
    { "country": "Virgin Islands (U.S.)", "isoCountryCode": "VI", "emojiCode": "\uD83C\uDDFB\uD83C\uDDEE" },
    { "country": "Wallis and Futuna", "isoCountryCode": "WF", "emojiCode": "\uD83C\uDDFC\uD83C\uDDEB" },
    { "country": "Western Sahara", "isoCountryCode": "EH", "emojiCode": "\uD83C\uDDEA\uD83C\uDDED" },
    { "country": "Yemen", "isoCountryCode": "YE", "emojiCode": "\uD83C\uDDFE\uD83C\uDDEA" },
    { "country": "Zambia", "isoCountryCode": "ZM", "emojiCode": "\uD83C\uDDFF\uD83C\uDDF2" },
    { "country": "Zimbabwe", "isoCountryCode": "ZW", "emojiCode": "\uD83C\uDDFF\uD83C\uDDFC" }
]